apiVersion: apps/v1
kind: Deployment

metadata:
  name: maven

spec:
  replicas: 1

  selector:
    matchLabels:
      app: maven

  template:
    metadata:
      labels:
        app: maven

    spec:
      containers:
      - name: mavenapp
        image: gaganahs/repomaven:latest
        ports:
        - containerPort: 8080
